services:
  watcher:
    environment:
      - DEBUG=1
    # Example: Uncomment to mount local code for hot reload in staging
    # volumes:
    #   - ./watcher:/app
    #   - ./shared:/app/shared

  metadata:
    environment:
      - DEBUG=1
    # volumes:
    #   - ./metadata:/app
    #   - ./shared:/app/shared

  splitter:
    environment:
      - DEBUG=1
    # volumes:
    #   - ./splitter:/app
    #   - ./shared:/app/shared

  packager:
    environment:
      - DEBUG=1
    # volumes:
    #   - ./packager:/app
    #   - ./shared:/app/shared

  organizer:
    environment:
      - DEBUG=1
    # volumes:
    #   - ./organizer:/app
    #   - ./shared:/app/shared

  telegram_youtube_bot:
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN_STAGING}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID_STAGING}
      - DEBUG=1
    # volumes:
    #   - ./telegram_youtube_bot:/app
    #   - ./shared:/app/shared

  status-api:
    environment:
      - DEBUG=1
    ports:
      - "5001:5001"
    # volumes:
    #   - ./status-api:/app
    #   - ./shared:/app/shared

  maintenance:
    environment:
      - DEBUG=1
    # volumes:
    #   - ./maintenance:/app
    #   - ./shared:/app/shared

  redis:
    image: redis:7-alpine
    restart: unless-stopped

networks:
  default:
    name: karaoke-mvp_default
