services:
  ${STACK_PREFIX}_init_chown_input:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_queue:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_stems:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_output:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_organized:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_metadata_json:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_splitter_tmp:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_grafana_config:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_init_chown_jellyfin_config:
    networks:
      - ${BACKEND_NETWORK}

networks:
  ${BACKEND_NETWORK}:
    external: true
