version: "3.8"

services:
  watcher:
    environment:
      - DEBUG=1

  metadata:
    environment:
      - DEBUG=1

  splitter:
    environment:
      - DEBUG=1

  packager:
    environment:
      - DEBUG=1

  organizer:
    environment:
      - DEBUG=1

  telegram_youtube_bot:
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN_STAGING}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID_STAGING}
      - DEBUG=1

  status-api:
    environment:
      - DEBUG=1
    ports:
      - "5001:5001"

  maintenance:
    environment:
      - DEBUG=1

  redis:
    # Optionally, point to a staging Redis server/cluster
    image: redis:7-alpine
    restart: unless-stopped

# Optionally, override volumes or networks for staging storage or metrics
