services:
  ${STACK_PREFIX}_dev_redis:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_watcher:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_metadata:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_splitter:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_packager:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_organizer:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_status_api:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_maintenance:
    networks:
      - ${BACKEND_NETWORK}

  ${STACK_PREFIX}_dev_telegram_youtube_bot:
    networks:
      - ${BACKEND_NETWORK}

networks:
  ${BACKEND_NETWORK}:
    external: true
