services:
  redis:
    image: redis:7-alpine
    container_name: karaoke_redis
    restart: unless-stopped

  watcher:
    image: ghcr.io/svidal-nlive/karaoke-watcher:latest
    container_name: karaoke_watcher
    depends_on:
      - redis
    volumes:
      - input:/input
      - queue:/queue
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  metadata:
    image: ghcr.io/svidal-nlive/karaoke-metadata:latest
    container_name: karaoke_metadata
    depends_on:
      - watcher
      - redis
    volumes:
      - queue:/queue
      - metadata_json:/metadata/json
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  splitter:
    image: ghcr.io/svidal-nlive/karaoke-splitter:latest
    container_name: karaoke_splitter
    depends_on:
      - metadata
      - redis
    volumes:
      - queue:/queue
      - stems:/stems
      - splitter_tmp:/tmp
      - ./models:/app/pretrained_models
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    healthcheck:
      test: ["CMD", "bash", "-c", "exit 0"]
      interval: 30s
      retries: 3

  packager:
    image: ghcr.io/svidal-nlive/karaoke-packager:latest
    container_name: karaoke_packager
    depends_on:
      - splitter
      - redis
    volumes:
      - stems:/stems
      - metadata_json:/metadata/json
      - output:/output
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  organizer:
    image: ghcr.io/svidal-nlive/karaoke-organizer:latest
    container_name: karaoke_organizer
    depends_on:
      - packager
      - redis
    volumes:
      - output:/output
      - organized:/organized
      - metadata_json:/metadata/json
    environment:
      - REDIS_HOST=redis
      - OUTPUT_DIR=/output
      - ORG_DIR=/organized
      - LOGS_DIR=/logs
      - META_DIR=/metadata
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

  status-api:
    image: ghcr.io/svidal-nlive/karaoke-status-api:latest
    container_name: karaoke_status_api
    depends_on:
      - organizer
      - redis
    ports:
      - "5001:5001"
    volumes:
      - input:/input
      - queue:/queue
      - metadata_json:/metadata/json
      - stems:/stems
      - output:/output
      - organized:/organized
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      retries: 3

  maintenance:
    image: ghcr.io/svidal-nlive/karaoke-maintenance:latest
    container_name: karaoke_maintenance
    depends_on:
      - redis
    volumes:
      - metadata_json:/metadata/json
      - stems:/stems
      - output:/output
      - queue:/queue
      - organized:/organized
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    entrypoint: ["python", "cleanup.py"]

  maintenance-cron:
    image: ghcr.io/svidal-nlive/karaoke-maintenance:latest
    container_name: karaoke_maintenance_cron
    depends_on:
      - redis
    volumes:
      - metadata_json:/metadata/json
      - stems:/stems
      - output:/output
      - queue:/queue
      - organized:/organized
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
    command: ["sh", "-c", "crontab /app/crontab && cron -f"]

  telegram_youtube_bot:
    image: ghcr.io/svidal-nlive/karaoke-telegram_youtube_bot:latest
    container_name: telegram_youtube_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - YTDLP_OUTPUT_DIR=/input
      - METADATA_OUTPUT_DIR=/metadata
    volumes:
      - input:/input
      - metadata_json:/metadata/json
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  input:
  queue:
  stems:
  output:
  organized:
  splitter_tmp:

  metadata_json:
networks:
  default:
    name: karaoke-mvp_default
