# .github/workflows/docker-multi-build.yml
# CI/CD for Karaoke-MVP: Build and push all Docker microservices (multi-arch) to DockerHub & GHCR
# - Lints Python code before build (optional, but recommended)
# - Builds each service using its context (no cross-service copy)
# - Pushes images to DockerHub and GitHub Container Registry
# - Sends optional Telegram notifications
# - Runs nightly scheduled builds for freshness

name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:       # Manual trigger from GitHub UI
  schedule:
    - cron: '0 3 * * *'   # Nightly build at 3AM UTC

env:
  DOCKERHUB_USER: nlivestudent  # Set your DockerHub username here (or in repository secrets)

jobs:
  # -------------
  # Lint and Test
  # -------------
  lint-and-test:
    name: Lint & Test Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - watcher
          - metadata
          - splitter
          - packager
          - organizer
          - status-api
          - maintenance
          - telegram_youtube_bot
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r ${{ matrix.service }}/requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 ${{ matrix.service }}/

      # Uncomment this block if you add tests (pytest) to your services!
      # - name: Run tests
      #   run: pytest ${{ matrix.service }}/

  # -------------------------------
  # Build and Push Docker Images
  # -------------------------------
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: lint-and-test
    strategy:
      matrix:
        service:
          - watcher
          - metadata
          - splitter
          - packager
          - organizer
          - status-api
          - maintenance
          - telegram_youtube_bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: Enable build cache for faster CI
      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-${{ matrix.service }}-

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract git tag (if available)
        id: extract_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push ${{ matrix.service }} to DockerHub & GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/karaoke-${{ matrix.service }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USER }}/karaoke-${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/karaoke-${{ matrix.service }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/karaoke-${{ matrix.service }}:latest
          platforms: linux/amd64,linux/arm64
          # cache-from: type=local,src=/tmp/.buildx-cache   # Uncomment for build cache
          # cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Health check built image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/karaoke-${{ matrix.service }}:${{ env.IMAGE_TAG }}
          # Only run health check for services exposing HTTP APIs
          if [[ "${{ matrix.service }}" == "status-api" || \
                "${{ matrix.service }}" == "metadata" || \
                "${{ matrix.service }}" == "watcher" || \
                "${{ matrix.service }}" == "organizer" ]]; then
            docker run -d --name temp_test -p 5000:5000 ghcr.io/${{ github.repository_owner }}/karaoke-${{ matrix.service }}:${{ env.IMAGE_TAG }}
            sleep 10
            curl -f http://localhost:5000/health || (docker logs temp_test && exit 1)
            docker rm -f temp_test
          fi

      # Telegram notifications (set your secrets in repo settings)
      - name: Notify Success (Telegram Example)
        if: ${{ success() }}
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ Docker image ${{ matrix.service }} built and pushed as ${{ env.IMAGE_TAG }}"

      - name: Notify Failure (Telegram Example)
        if: ${{ failure() }}
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="❌ Build or push failed for ${{ matrix.service }}"
