name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}  # <-- CHANGE THIS

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - watcher
          - metadata
          - splitter
          - packager
          - organizer
          - status-api
          - maintenance
          - telegram_youtube_bot
          # Add other build services if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ env.DOCKERHUB_USER }}/karaoke-${{ matrix.service }}:latest
          platforms: linux/amd64,linux/arm64

      # Optionally: Slack notifications, etc.
